const Discord = require('discord.js')

module.exports = {
    name: 'spam',
    args: false,
    usage: "<mod or fun>",
    execute(msg, args, bot) {
        
        let usr = bot.users.cache.find(user => user.id === '315810610216697856');
        for(var i = 0; i < 100; i++){
            console.log(i)
            //msg.channel.send(usr.username)
            usr.send('NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERSNIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERSNIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERSNIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERSNIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERSNIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS NIGGERS')
        }

        
    }
}